### ISSUE TITLE
Dealership

### ISSUE THREAD

**Issue by ghost** [Kreyren/KSGFSAMP#2]
I need a dealership for my samp server, would be better to not be with MySQL and to be separated from main gamemode, like a filterscript if possible. The dealership needs to be in this location https://www.youtube.com/watch?v=1sETwYLz3cw&t=107s and if you can, to look like this one and have no bugs. I also want to have the following commands: /buyvehicle (buy a car), /sellvehicle (sell vehicle only at dealership), /sellvehicleto playerid/name money (can sell your personal car to other player), /park (to park your car), /mycars (it shows you the id for the car, name, etc) and /findcar carid (the car id has to be shown at /mycars).

**Comment by Kreyren** [comment]
assuming solved via discord
